package bot

import "path/filepath"

const API_KEY = "5360047799:AAE95DZ1rnPnxP5vLbkcOVREYGfPFqARbQs"

var BOT_USERNAME = ""

const UNKNOWN_ERROR = "مشکلی پیش امد, دوباره امتحان کنید."

var PICTURES_DIRECTORY = filepath.Join("../pictures/books/")

var BOT_START_QUERY = "https://t.me/%s/?start=%d"

var ENTERED_VALUE_IS_INVALID_ERROR = "مقدار وارد شده نامعتبر است."
var BOOK_NOT_SAVED_IN_DATABASE = "عملیات ذخیره کردن کتاب در دیتابیس ناموفق بود."
var ENTERED_NON_NUMBER_VALUE_ERROR = "لطفا عددی را به عنوان مقدار وارد کنید."
var YOU_HAVE_NOT_ADDRESS_INLINE_KEYBOARD_MESSAGE = "شما ادرسی را تنظیم نکرده اید, برای تنظیم ادرس بر روی دکمه ی زیر کلیک کنید."
var CONTACT_TO_ADMIN_MESSAGE = "با کلیک بر روی دکمه ی زیر میتوانید با ادمین ارتباط داشته باشید"
var EMPTY_STRING = ""
var DELETE_STRING = "حذف"
var ENTER_SEARCH_PHRASE_TEXT = "وارد کردن عبارت حستجو"
var ENTER_SEARCH_PHRASE_FOR_DELETE_BOOK_TEXT = "وارد کردن عبارت جستجو برای حذف"
var SEARCH_FOR_DELETE_BOOK_MESSAGE_TEXT = "با استفاده از گزینه ی زیر میتوانید کتابی را برای حذف انتخاب کنید"
var START_TEXT = "start"
var BUY_CART_MESSAGE_HEADER = "لطفا مبلغ درج شده را به شماره کارت زیر واریز کنید و بعد از <b>حتما</b> روی دکمه ی زیر کلیک کنید.\nپس از ان سفارش شما در صف تایید قرار میگیرد و میتوانید از طریق منو اصلی برنامه بر روی دکمه ی سفارش ها کلیک کنید و وضعیت سفارش خود را ببینید.\n"
var BUY_CART_MESSAGE_FOOTER = ""
var CART_IS_EMPTY = "سبد خرید خالی هست !"
var BUY_CART_MESSAGE = ""
var CART_MESSAGE_HEADER = ""
var CART_MESSAGE_FOOTER = ""
var ADMIN_START_TEXT = "admin start"
var AT_LEAST_ENTER_ONE_CHARACTER_ERROR = "لطفا حداقل یک کاراکتر برای جستجو وارد کنید."
var ENTERED_PHRASE_IS_TOO_SHORT_ERROR = "عبارت وارد شده بیش از حد کوتاه است."
var NO_RESULT_FOUND_ERROR = "نتیجه ای یافت نشد."
var NO_RESULT_FOUND_DESCRIPTION_FORMAT_ERROR = "برای عبارت %s نتیجه ای یافت نشد.\nعنوان کتاب را بررسی کنید, همچنین امکان دارد کتاب موجود نباشد."
var SEARCH_TEXT = "you can search by pressing below button"
var REQUEST_BOOK_PICTURE = "عکس های کتاب را در یک پیام ارسال کنید."
var YOU_ALREADY_HAVE_ADDRESS = "شما قبلا ادرسی را وارد کرده اید."
var SHOW_USER_ADDRESS_FORMATTED = "کشور: %s\nاستان: %s\nشهر: %s\nخیابان: %s\nشماره ی ساختمان: %s\nکد پستی: %s\nشماره تلفن: %s\nتوضیحات: %s\n"
var CLICK_FOR_EDIT_ADDRESS_INLINE_KEYBOARD_ITEM_TITLE = "برای تغییر ادرس کلیک کنید!"
var REQUEST_BOOK_WEIGHT = "وزن کتاب را وارد کنید (گرم)."
var REQUEST_BOOK_ISBN = "isbn"
var REQUEST_BOOK_TITLE = "عنوان کتاب را وارد کنید :"
var REQUEST_BOOK_AUTHOR = "author"
var REQUEST_BOOK_TRANSLATOR = "translator"
var REQUEST_BOOK_PAPER_TYPE = "paper type"
var REQUEST_BOOK_DESCRIPTION = "description"
var REQUEST_BOOK_NUMBER_OF_PAGES = "number of pages"
var REQUEST_BOOK_GENRE = "genre"
var REQUEST_BOOK_CENSORED_STATUS = "censored status"
var REQUEST_BOOK_PUBLISHER = "publisher"
var REQUEST_BOOK_PUBLISHDATE = "publish date"
var REQUEST_BOOK_PRICE = "price"
var REQUEST_BOOK_AZERO_SCORE = "arezo score"
var REQUEST_BOOK_COVERTYPE = "select cover type"
var REQUEST_BOOK_SIZE = "select book size"
var REQUEST_BOOK_AGE_CATEGORY = "select age category"

// Address
var REQUEST_ADDRESS_COUNTRY = "کدام کشور هستید؟"
var REQUEST_ADDRESS_PROVINCE = "کدام استان هستید؟"
var REQUEST_ADDRESS_CITY = "کدام شهر هستید؟"
var REQUEST_ADDRESS_STREET = "کدام خیابان/کوچه هستید؟"
var REQUEST_ADDRESS_BUILDING_NUMBER = "کدام نام/شماره ساختمان هستید؟"
var REQUEST_ADDRESS_POSTAL_CODE = "کد پستی شما چیست؟"
var REQUEST_ADDRESS_DESCRIPTION = "میتوانید توضیحاتی را اینجا بنویسید!"
var REQUEST_ADDRESS_PHONE_NUMBER = "شماره همراهتان را بنویسید"
var BOOK_INFORMATION_FORMAT = "عنوان: %s\nنویسنده: %s\nمترجم: %s\nتعداد صفحات: %d\nدسته بندی: %s\nوضعیت سانسور: %s\nنوع جلد: %s\nسایز: %s\nرده سنی: %s\nامتیاز گودریدز: %s\nامتیاز ارزو: %s\nانتشارات: %s\nتاریخ انتشار: %s\nشابک: %s\nقیمت: %s\n\n@%s"
var BOOK_DELETED_SUCCESSFULY = "کتاب %s حدف شد."

var ADD_BOOK_TO_CART = "اضافه کردن به سبد خرید"
var DELETE_BOOK_FROM_CART = "حدف از سبد خرید"
var BOOK_DELETED_FROM_CART_FORMAT = "کتاب %s از سبد خرید حذف شد."
var BOOK_NOT_ADDED_TO_CART = "کتاب به سبد حرید اضافه نشد."
var BOOK_ADDED_TO_CART_SUCCESSFULY = "کتاب به سبد خرید اضافه شد."
var SWITCH_TO_PV_FORMAT = "https://t.me/%s"
var ADDRESS_ADDED_MESSAGE = "ادرس شما تنظیم شد"
